kind = "web"
previewPath = "/"
title = "NS Record-File Viewer"
version = "1.0.0"
id = "artifacts/ns-file-viewer"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24264

[services.development]
run = "pnpm --filter @workspace/ns-file-viewer run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ns-file-viewer", "run", "build" ]
publicDir = "artifacts/ns-file-viewer/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24264"
BASE_PATH = "/"
